name: remote_control
description: "App di controllo remoto per PC — touchpad, click e tastiera via TCP/HTTP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.4
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
